# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'proManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for proManager

  target 'proManager-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'proManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'proManager-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for proManager-tvOS



end
